version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: meforyou-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: meforyou-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  web:
    build: .
    container_name: meforyou-web
    command: bash -c "bundle install && rails db:migrate && rails s -b 0.0.0.0 -p ${PORT}"
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  sidekiq:
    build: .
    container_name: meforyou-sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    env_file:
      - .env


volumes:
    pgdata:
    redisdata:
