version: "3.9"
services:
  app:
    build: .
    container_name: meforyou_ai_app
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: bash -c "bundle exec rails db:prepare && bundle exec puma -C config/puma.rb"

  db:
    image: postgres:15
    container_name: meforyou_ai_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meforyou_ai_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: meforyou_ai_redis
    ports:
      - "6379:6379"

volumes:
  pg_data:
