default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: meforyou_ai_db

test:
  <<: *default
  database: meforyou_ai_db_test

production:
  <<: *default
  database: meforyou_ai_production
