default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "127.0.0.1" } %>
  port: 5432
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "meforyou_ai_db" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "meforyou_ai_db_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "meforyou_ai_production" } %>
