default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: 5432
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_DEVELOPMENT") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_TEST") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_PRODUCTION") %>
